config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("core.urls")),
    path("groups/", include("groups.urls")),
]

core/urls.py
from django.urls import path
from .views import home, students_list

urlpatterns = [
    path("", home, name="home"),
    path("students/", students_list, name="students_list"),
]

groups/urls.py
from django.urls import path
from .views import create_group, group_list, group_detail, department_list, create_department, department_edit, delete_group, upload_file

urlpatterns = [
    path("create_group/", create_group, name="create_group"),
    path("create_department/", create_department, name="create_department"),
    path("departments/<int:pk>/", department_edit, name="department_edit"),
    path("departments/", department_list, name="department_list"),
    path("group/<int:pk>/", group_detail, name="group_detail"),
    path("group/delete/<int:pk>/", delete_group, name="group_delete"),
    path("upload_file/", upload_file, name="upload_file"),
    path("", group_list, name="group_list"),
]

groups/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=50, unique=True)
    department = models.ManyToManyField(Department, related_name="groups", blank=True)

    def __str__(self):
        return self.name

class DepartmentFile(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="files")
    uploaded_by = models.ForeignKey("accounts.User", on_delete=models.SET_NULL, null=True)
    file = models.FileField(upload_to="department_files/")
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.file.name} ({self.department.name})"


class GroupFile(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name="files")
    uploaded_by = models.ForeignKey("accounts.User", on_delete=models.SET_NULL, null=True)
    file = models.FileField(upload_to="group_files/")
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.file.name} ({self.group.name})"

groups/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import Group, Department, DepartmentFile, GroupFile
from accounts.models import StudentProfile

User = get_user_model()

# Create your views here.
@login_required
def create_group(request):
    if request.user.role not in ["teacher", "admin"]:
        redirect("home")

    if request.method == "POST":
        name = request.POST.get("name")
        group = Group.objects.create(name=name)
        return redirect("group_list")

    return render(request, "groups/create_group.html")

@login_required
def delete_group(request, pk):
    if request.user.role not in ["teacher", "admin"]:
        redirect("home")

    group = get_object_or_404(Group, id=pk)
    group.delete()
    return redirect("group_list")


@login_required
def group_list(request):
    if request.user.role not in ["teacher", "admin"]:
        redirect("home")

    groups = Group.objects.all()
    return render(request, "groups/group_list.html", {"groups": groups})

@login_required
def group_detail(request, pk):
    if request.user.role not in ["teacher", "admin"]:
        redirect("home")

    group = get_object_or_404(Group, pk=pk)
    students = group.students.all()
    # students = User.objects.filter(groups=group)

    if request.method == "POST":
        action = request.POST.get("action")
        student_profile_id = request.POST.get("student_id")
        student = get_object_or_404(StudentProfile, pk=student_profile_id)
        
        if action == "add":
            group.students.add(student)
        elif action == "remove":
            group.students.remove(student)

        return redirect("group_detail", pk=group.pk)

    available_students = StudentProfile.objects.filter(group__isnull=True)

    return render(request, "groups/group_detail.html", {
        "group": group,
        "students": students,
        "available_students": available_students
    })

@login_required
def department_list(request):
    if request.user.role not in ["teacher", "admin"]:
        redirect("home")

    departments = Department.objects.all()
    return render(request, "groups/department_list.html", {"departments": departments})


@login_required
def create_department(request):
    if request.user.role not in ["teacher", "admin"]:
        redirect("home")

    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")

        Department.objects.create(name=name, description=description, created_by=request.user)

        return redirect("department_list")

    return render(request, "groups/create_department.html")

@login_required
def department_edit(request, pk):
    if request.user.role not in ["teacher", "admin"]:
        redirect("home")

    department = get_object_or_404(Department, pk=pk)
    # groups = Group.objects.all()
    availbable_groups = Group.objects.exclude(department=department)

    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")

        if name:  # тільки якщо є
            department.name = name
        if description is not None:
            department.description = description
        department.save()

        selected_groups = request.POST.getlist("groups")
        department.groups.set(Group.objects.filter(id__in=selected_groups))

        return redirect("department_list")

    return render(request, "groups/department_edit.html", {
        "department": department,
        "availbable_groups": availbable_groups 
    })

@login_required
def upload_file(request):
    # доступ лише для викладача або адміна
    if request.user.role not in ["teacher", "admin"]:
        return redirect("home")

    departments = Department.objects.all()
    groups = Group.objects.all()

    if request.method == "POST":
        target_type = request.POST.get("target_type")  # "department" або "group"
        file = request.FILES.get("file")

        if target_type == "department":
            department_id = request.POST.get("department_id")
            department = get_object_or_404(Department, pk=department_id)
            DepartmentFile.objects.create(
                department=department,
                uploaded_by=request.user,
                file=file
            )

        elif target_type == "group":
            group_id = request.POST.get("group_id")
            group = get_object_or_404(Group, pk=group_id)
            GroupFile.objects.create(
                group=group,
                uploaded_by=request.user,
                file=file
            )

        return redirect("home")  # після завантаження можна редіректнути куди треба

    return render(request, "groups/upload_file.html", {
        "departments": departments,
        "groups": groups,
    })

groups/templates/groups/create_department.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container py-4">
  <h2 class="mb-3">Створити кафедру</h2>

  <!-- Повідомлення про помилки/успіх (якщо використовуєш messages framework) -->
  {% if messages %}
    <div class="mb-3">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}

  <!-- Форма створення кафедри -->
  <form method="post" class="card shadow-sm">
    {% csrf_token %}
    <div class="card-body">
      <div class="mb-3">
        <label for="id_name" class="form-label">Назва кафедри</label>
        <input
          type="text"
          name="name"
          id="id_name"
          class="form-control"
          placeholder="Наприклад: Кафедра математики"
          required
          value="{{ request.POST.name|default:'' }}"
        >
        {% if form and form.errors.name %}
          <div class="text-danger small mt-1">{{ form.errors.name.0 }}</div>
        {% endif %}
      </div>

      <div class="mb-3">
        <label for="id_description" class="form-label">Опис</label>
        <textarea
          name="description"
          id="id_description"
          class="form-control"
          rows="3"
          placeholder="Короткий опис кафедри"
        >{{ request.POST.description|default:'' }}</textarea>
        {% if form and form.errors.description %}
          <div class="text-danger small mt-1">{{ form.errors.description.0 }}</div>
        {% endif %}
      </div>

      <!-- Необов’язково: одразу прив’язати групи до кафедри (ManyToMany) -->
      {% if groups %}
        <div class="mb-3">
          <label for="id_groups" class="form-label">Додати групи до кафедри (необов’язково)</label>
          <select
            name="group_ids"
            id="id_groups"
            class="form-select"
            multiple
          >
            {% for group in groups %}
              <option value="{{ group.id }}">{{ group.name }}</option>
            {% endfor %}
          </select>
          <div class="form-text">Утримуй Ctrl (Windows/Linux) або Cmd (macOS), щоб вибрати кілька груп.</div>
        </div>
      {% endif %}
    </div>

    <div class="card-footer d-flex gap-2">
      <button type="submit" class="btn btn-primary">Створити</button>
      <a href="{% url 'department_list' %}" class="btn btn-outline-secondary">До списку кафедр</a>
    </div>
  </form>
</div>
{% endblock %}

groups/templates/groups/create_group.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Створити нову групу</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Назва групи</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Створити</button>
    </form>
</div>
{% endblock %}

groups/templates/groups/department_edit.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
  <h2>Редагувати кафедру</h2>
  <form method="post" id="departmentForm">
    {% csrf_token %}
    <div class="row">
        <!-- Поле для назви --> 
        <div class="mb-3"> 
            <label for="id_name" class="form-label">Назва кафедри</label> 
            <input type="text" name="name" id="id_name" class="form-control" value="{{ department.name }}" required> 
        </div> 
        <!-- Поле для опису --> 
        <div class="mb-3"> 
            <label for="id_description" class="form-label">Опис</label> 
            <textarea name="description" id="id_description" class="form-control">{{ department.description }}</textarea> 

        </div>
      <!-- Ліва колонка -->
      <div class="col-md-5">
        <h5>Доступні групи</h5>
        <select id="availableGroups" class="form-select" size="10" multiple>
          {% for group in availbable_groups %}
            {% if group not in department.groups.all %}
              <option value="{{ group.id }}">{{ group.name }}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>

      <!-- Кнопки -->
      <div class="col-md-2 d-flex flex-column justify-content-center align-items-center">
        <button type="button" id="addGroup" class="btn btn-primary mb-2">&gt;&gt;</button>
        <button type="button" id="removeGroup" class="btn btn-secondary">&lt;&lt;</button>
      </div>

      <!-- Права колонка -->
      <div class="col-md-5">
        <h5>Групи кафедри</h5>
        <select id="departmentGroups" name="groups" class="form-select" size="10" multiple>
          {% for group in department.groups.all %}
            <option value="{{ group.id }}">{{ group.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>

    <div class="mt-3">
      <button type="submit" class="btn btn-success">Зберегти</button>
      <a href="{% url 'department_list' %}" class="btn btn-secondary">Назад</a>
    </div>
  </form>
</div>

<script>
  const available = document.getElementById("availableGroups");
  const selected = document.getElementById("departmentGroups");
  const addBtn = document.getElementById("addGroup");
  const removeBtn = document.getElementById("removeGroup");

  addBtn.addEventListener("click", () => {
    [...available.selectedOptions].forEach(opt => {
      selected.appendChild(opt);
    });
  });

  removeBtn.addEventListener("click", () => {
    [...selected.selectedOptions].forEach(opt => {
      available.appendChild(opt);
    });
  });

  // Перед сабмітом позначаємо всі групи справа як вибрані
  document.getElementById("departmentForm").addEventListener("submit", () => {
    [...selected.options].forEach(opt => opt.selected = true);
  });
</script>
{% endblock %}

groups/templates/groups/department_list.html
{% extends "base.html" %}

{% block title %}Список груп{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mb-4">Список кафедр</h2>

    <a href="{% url 'create_department' %}" class="btn btn-primary mb-3">Створити нову кафедру</a>

    <div class="row">
        {% for department in departments %}
            <div class="col-md-6 mb-3">
                <div class="card shadow-sm">
                    <div class="card-body">
                      <a href="{% url 'department_edit' pk=department.id %}">{{ department.name }}</a>
                        <p>Кількість Груп: {{ department.group.all|length }}</p>
                    </div>
                </div>
            </div>
        {% empty %}
            <p class="text-muted">Групи ще не створені.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Група {{ group.name }}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Група {{ group.name }}</h2>

    <h4>Студенти у групі:</h4>
    <ul>
        {% for student in students %}
            <li>
                {{ student.user.username }}
                <form method="post" style="display:inline;">
                    {% csrf_token %}
                    <input type="hidden" name="student_id" value="{{ student.id }}">
                    <input type="hidden" name="action" value="remove">
                    <button type="submit" class="btn btn-sm btn-danger">Видалити</button>
                </form>
            </li>
        {% empty %}
            <li class="text-muted">Немає студентів у групі</li>
        {% endfor %}
    </ul>

    <h4 class="mt-4">Додати студента:</h4>
    <form method="post">
        {% csrf_token %}
        <select name="student_id" class="form-select mb-2">
            {% for student in available_students %}
                <option value="{{ student.id }}">{{ student.user.username }}</option>
            {% endfor %}
        </select>
        <input type="hidden" name="action" value="add">
        <button type="submit" class="btn btn-primary">Додати</button>
    </form>
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "base.html" %}

{% block title %}Список груп{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mb-4">Список груп</h2>

    <a href="{% url 'create_group' %}" class="btn btn-primary mb-3">Створити нову групу</a>

    <div class="row">
        {% for group in groups %}
            <div class="col-md-6 mb-3">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <a href="{% url 'group_detail' pk=group.id %}">{{ group.name }}</a>
                        <p>Кількість студентів: {{ group.students.all|length }}</p>
                        <a href="{% url 'group_delete' pk=group.id %}">Видалити<a>
                        <a href="{% url 'upload_file' %}">Завантажити<a>
                    </div>
                </div>
            </div>
        {% empty %}
            <p class="text-muted">Групи ще не створені.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

groups/templates/groups/upload_file.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
  <h2>Завантажити файл</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- Вибір типу -->
    <div class="mb-3">
      <label class="form-label">Куди завантажити?</label>
      <select name="target_type" id="target_type" class="form-select" required>
        <option value="department">На кафедру</option>
        <option value="group">У групу</option>
      </select>
    </div>

    <!-- Селект кафедри -->
    <div class="mb-3" id="department_select">
      <label class="form-label">Виберіть кафедру</label>
      <select name="department_id" class="form-select">
        {% for department in departments %}
          <option value="{{ department.id }}">{{ department.name }}</option>
        {% endfor %}
      </select>
    </div>

    <!-- Селект групи -->
    <div class="mb-3" id="group_select" style="display:none;">
      <label class="form-label">Виберіть групу</label>
      <select name="group_id" class="form-select">
        {% for group in groups %}
          <option value="{{ group.id }}">{{ group.name }}</option>
        {% endfor %}
      </select>
    </div>

    <!-- Файл -->
    <div class="mb-3">
      <label class="form-label">Файл</label>
      <input type="file" name="file" class="form-control" required>
    </div>

    <button type="submit" class="btn btn-primary">Завантажити</button>
  </form>
</div>

<script>
  const targetType = document.getElementById("target_type");
  const depSelect = document.getElementById("department_select");
  const groupSelect = document.getElementById("group_select");

  targetType.addEventListener("change", () => {
    if (targetType.value === "department") {
      depSelect.style.display = "block";
      groupSelect.style.display = "none";
    } else {
      depSelect.style.display = "none";
      groupSelect.style.display = "block";
    }
  });
</script>
{% endblock %}