accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import reqister_user, delete_student, edit_student, student_profile

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path("register/", reqister_user, name="register"),
    path("profile/", student_profile, name="profile"),
    path("students/delete/<int:pk>/", delete_student, name="delete_student"),
    path("students/edit/<int:pk>/", edit_student, name="edit_student"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("core.urls")),
    path("groups/", include("groups.urls")),
]

core/urls.py
from django.urls import path
from .views import home, students_list

urlpatterns = [
    path("", home, name="home"),
    path("students/", students_list, name="students_list"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    ROLE_CHOISE = (
        # "studnet" покаже в базі "Student" покаже на сайті для адміна
        ("student", "Student"),
        ("teacher", "Teacher"),
        ("admin", "Admin"),
    )
    # Вибираємо роль для користувача для деф буде студент
    role = models.CharField(max_length=20, choices=ROLE_CHOISE, default="student")

    def __str__(self):
        return f"{self.username} ({self.role})"

class StudentProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    group = models.ForeignKey("groups.Group", on_delete=models.SET_NULL, null=True, blank=True, related_name="students")

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from .models import User, StudentProfile

class UserCrateForm(forms.ModelForm):
    # Для того щоб у формі було <input type="password">
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "email", "password", "role"]

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
            if user.role == "student":
                StudentProfile.objects.create(user=user)

        return user

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from .models import StudentProfile, User
from .forms import UserCrateForm

@login_required
def reqister_user(request):
    if request.user.role not in ["admin", "teacher"]:
        return redirect("home")
    
    if request.method == "POST":
        form = UserCrateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = UserCrateForm()
    
    return render(request, "accounts/register.html", {"form": form})

@login_required
def delete_student(request, pk):
    if request.user.role not in ["admin", "teacher"]:
        return redirect("home")

    student = get_object_or_404(StudentProfile, pk=pk)
    student.delete()
    return redirect("students_list")

@login_required
def edit_student(request, pk):
    if request.user.role != "admin":
        return redirect("home")

    user = get_object_or_404(User, id=pk)

    if request.method == "POST": 
        user.username = request.POST.get("username") 
        password = request.POST.get("password") 
        if password: # якщо пароль введено 
            user.password = make_password(password) 
        user.save() 
        return redirect("students_list") 
    return render(request, "accounts/edit_student.html", {"user": user})

@login_required
def student_profile(request):
    # беремо поточного користувача
    student = get_object_or_404(User, pk=request.user.id)
    student_profile = get_object_or_404(StudentProfile, user=request.user)

    # група студента
    group = student_profile.group

    # файли групи
    group_files = group.files.all() if group else []

    # файли кафедри
    department_files = []
    if group:
        for dep in group.department.all():
            department_files += list(dep.files.all())

    return render(request, "accounts/profile.html", {
        "student": student,
        "group": group,
        "group_files": group_files,
        "department_files": department_files,
    })

accounts/templates/accounts/edit_student.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Редагувати користувача</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_username" class="form-label">Ім’я користувача</label>
            <input type="text" name="username" id="id_username"
                   class="form-control" value="{{ user.username }}" required>
        </div>
        <div class="mb-3">
            <label for="id_password" class="form-label">Новий пароль (необов’язково)</label>
            <input type="password" name="password" id="id_password" class="form-control">
            <div class="form-text">Залиш порожнім, якщо не хочеш змінювати пароль.</div>
        </div>
        <button type="submit" class="btn btn-primary">Зберегти</button>
        <a href="{% url 'students_list' %}" class="btn btn-secondary">Назад</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="container vh-100 d-flex justify-content-center align-items-center">
{% if form.errors %}
  <p style="color:red;">Неправильний логін або пароль. Спробуйте ще раз.</p>
{% endif %}
<form class="text-center" method="POST">
  {% csrf_token %}
  <img class="mb-4" src={% static 'imgs/icon.png' %} alt="" width="72" height="110">
    <h1 class="h3 mb-3 fw-normal">Будьласка увійдіть у систему</h1>

    <label for="username">Username</label>
    <div class="form-floating mb-3">
      {{ form.username }}
    </div>
    <label for="password">Password</label>
    <div class="form-floating">
      {{ form.password }}
    </div>

    <button class="w-100 btn btn-lg mt-3 btn-success" type="submit">Вхід</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
  <h2>👤 Кабінет студента: {{ student.username }}</h2>

  {% if group %}
    <p><strong>Група:</strong> {{ group.name }}</p>
  {% else %}
    <p>Ви ще не належите до жодної групи.</p>
  {% endif %}

  <h3 class="mt-4">📂 Файли групи</h3>
  {% if group_files %}
    <ul class="list-group mb-3">
      {% for f in group_files %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ f.file.name|slice:"15:" }}
          <span class="badge bg-info text-dark">Автор: {{ f.uploaded_by.username }}</span>
          <a href="{{ f.file.url }}" class="btn btn-sm btn-primary">Завантажити</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Файлів у групі ще немає.</p>
  {% endif %}

  <h3 class="mt-4">🏛 Файли кафедри</h3>
  {% if department_files %}
    <ul class="list-group">
      {% for f in department_files %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ f.file.name|slice:"15:" }}
          <span class="badge bg-secondary">Автор: {{ f.uploaded_by.username }}</span>
          <a href="{{ f.file.url }}" class="btn btn-sm btn-primary">Завантажити</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Файлів на кафедрі ще немає.</p>
  {% endif %}
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}
 
{% block content %}
  <h2>Реєстрація нового користувача</h2>

  {% if form.errors %}
    <p style="color:red;">Будь ласка, виправте помилки у формі.</p>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <div>
      <label for="id_username">Ім'я користувача:</label>
      {{ form.username }}
    </div>
    <div>
      <label for="id_email">Email:</label>
      {{ form.email }}
    </div>
    <div>
      <label for="id_password">Пароль:</label>
      {{ form.password }}
    </div>
    <div>
      <label for="id_role">Роль:</label>
      {{ form.role }}
    </div>
    <button type="submit">Зареєструвати</button>
  </form>


<form> 
  <img class="mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> 
  <h1 class="h3 mb-3 fw-normal">Please sign in</h1> 
  <div class="form-floating"> 
    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com"> 
    <label for="floatingInput">Email address</label> 

  </div> 
  <div class="form-floating"> 
    <input type="password" class="form-control" id="floatingPassword" placeholder="Password"> 
    <label for="floatingPassword">Password</label> 
  </div> 
  <div class="form-check text-start my-3"> 
    <input class="form-check-input" type="checkbox" value="remember-me" id="checkDefault"> 
    <label class="form-check-label" for="checkDefault">Remember me</label> 

  </div> 
  <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button> 
  <p class="mt-5 mb-3 text-body-secondary">© 2017–2025</p> 
</form>


{% endblock %}